server:
  port: 8080

#jdbc
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/area?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: root
#mybatis
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.hanxx.area.entity